name: PyTorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hdf3f5d2_2
  - absl-py=2.0.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py310h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.22.1=h93a5062_0
  - ca-certificates=2023.11.17=hf0a4a13_0
  - cachetools=5.3.2=pyhd8ed1ab_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py310h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=39.0.1=py310h834c97f_2
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.9.0=py310hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.4.0=py310h80987f9_0
  - giflib=5.2.1=h80987f9_3
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py310h8c48613_0
  - google-auth=2.23.4=pyhca7485f_0
  - google-auth-oauthlib=1.1.0=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=hc60591f_1
  - idna=3.4=py310hca03da5_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyh3cd1d5f_0
  - ipython=8.16.1=pyh31c8845_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py310hca03da5_0
  - jpeg=9e=h80987f9_1
  - jupyter_client=8.5.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libabseil=20211102.0=cxx17_hc0b94f3_2
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.5.0=h313beb8_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.5.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h1a28f6b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=2.8.4=py310hca03da5_1
  - numpy=1.25.0=py310h3b2db8e_0
  - numpy-base=1.25.0=py310ha9811e2_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.1.4=h0d3ecfb_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h313beb8_0
  - pip=23.1.2=py310hca03da5_0
  - platformdirs=3.10.0=py310hca03da5_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.11=hb885b13_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h80987f9_1
  - pyzmq=25.1.0=py310h313beb8_0
  - re2=2022.04.01=h6b3803e_0
  - readline=8.2=h1a28f6b_0
  - requests=2.29.0=py310hca03da5_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - setuptools=67.8.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310hca03da5_0
  - tensorboard=2.15.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310ha6e5c4f_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.3.3=py310h80987f9_0
  - traitlets=5.12.0=pyhd8ed1ab_0
  - typing_extensions=4.6.3=py310hca03da5_0
  - urllib3=1.26.16=py310hca03da5_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.38.4=py310hca03da5_0
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - ace-tools==0.0
      - aiohttp==3.8.6
      - alembic==1.13.3
      - arrow==1.3.0
      - async-timeout==4.0.3
      - codecarbon==2.3.4
      - coloredlogs==15.0.1
      - colorlog==6.8.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - data==0.4
      - et-xmlfile==2.0.0
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - fsspec==2023.10.0
      - funcsigs==1.0.2
      - future==0.18.3
      - fuzzywuzzy==0.18.0
      - fvcore==0.1.5.post20221221
      - grpcio==1.60.0
      - h5py==3.10.0
      - hdf5plugin==4.4.0
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - imageio==2.34.2
      - imgaug==0.4.0
      - iopath==0.1.10
      - joblib==1.3.2
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - latex==0.7.0
      - lazy-loader==0.4
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - mako==1.3.5
      - matplotlib==3.8.0
      - mpmath==1.2.1
      - multidict==6.0.4
      - nexusformat==1.0.4
      - nir==0.2.0
      - nirtorch==0.2.1
      - onnx==1.15.0
      - onnxruntime==1.16.1
      - opencv-python==4.8.1.78
      - openpyxl==3.1.5
      - optuna==4.0.0
      - optuna-integration==4.0.0
      - pandas==2.1.2
      - patsy==0.5.3
      - plotly==5.18.0
      - plotly-express==0.4.1
      - portalocker==3.2.0
      - prometheus-client==0.19.0
      - protobuf==4.25.0
      - py-cpuinfo==9.0.0
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pytorch-lightning==2.1.0
      - pytz==2023.3.post1
      - rapidfuzz==3.6.1
      - regex==2023.10.3
      - safetensors==0.4.0
      - scienceplots==2.1.1
      - scikit-datasets==0.2.4
      - scikit-image==0.24.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.13.2
      - shapely==2.0.4
      - shutilwhich==1.1.0
      - snntorch==0.7.0
      - sqlalchemy==2.0.35
      - statsmodels==0.14.0
      - tabulate==0.9.0
      - tempdir==0.7.1
      - tenacity==8.2.3
      - tensorboard-logger==0.1.0
      - termcolor==3.1.0
      - threadpoolctl==3.2.0
      - tifffile==2024.7.2
      - tokenizers==0.14.1
      - torch==2.0.0
      - torchmetrics==1.2.0
      - torchsummary==1.5.1
      - torchvision==0.15.1
      - tqdm==4.66.1
      - transformers==4.34.1
      - types-python-dateutil==2.8.19.20240106
      - tzdata==2023.3
      - yacs==0.1.8
      - yarl==1.9.2
prefix: /Users/fernando/anaconda3/envs/PyTorch_env
