name: akida_tf_2x_keras_2x
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_0
  - python=3.10.18=h19e8193_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - codecarbon==3.0.7
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cryptography==46.0.2
      - cycler==0.12.1
      - dm-tree==0.1.9
      - exceptiongroup==1.3.0
      - fief-client==0.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.0
      - imgaug==0.4.0
      - joblib==1.5.2
      - jwcrypto==1.5.6
      - keras==2.15.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-ml-py==13.580.82
      - oauthlib==3.3.1
      - onnx==1.16.1
      - onnxruntime==1.19.2
      - onnxruntime-extensions==0.13.0
      - onnxscript==0.2.5
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==11.3.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - quantizeml==0.19.0
      - questionary==2.1.1
      - rapidfuzz==3.14.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.4.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metal==1.1.0
      - tensorflow-model-optimization==0.7.5
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - typer==0.19.2
      - types-python-dateutil==2.9.0.20251008
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - yaspin==3.3.0
prefix: /Users/fernando/anaconda3/envs/akida_tf_2x_keras_2x
